name: sms_bombing
description: Future Promotion 24H SMS Bomb
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.6+7

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.2.2
  intl: ^0.18.1
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  flutter_cupertino_datetime_picker: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - asset/